apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: "amqp://toto:toto1@localhost:5672/toto"
  - name: durable
    value: true
  - name: deletedWhenUnused
    value: false
  - name: consumerID
    value: channel1

